@echo off
title Hatsune Miku Bot 🥬
echo Starting Hatsune Miku Bot...
echo.
echo Checking and installing dependencies...
py -m pip install -r requirements.txt
echo.
echo Starting bot...
py main.py
echo.
echo Bot has stopped. Press any key to exit...
pause